sudo: required

language: c++

services:
  - docker

before_install:
    - docker pull benjaminn13/pid-workspace-ci:ubuntu-16.04
    - docker pull benjaminn13/pid-workspace-ci:ubuntu-18.04

script:
    - if [ $TRAVIS_BRANCH = 'master' ]; then docker run benjaminn13/pid-workspace-ci:ubuntu-16.04 bash -c "git config --global user.name "CI Bot" && git config --global user.email dontcare@CI.com && make upgrade && make deploy package=open-phri && cd ../packages/open-phri/build/ && cmake -DBUILD_AND_RUN_TESTS=ON .. && cmake .. && make build force=true"; fi
    - if [ $TRAVIS_BRANCH = 'master' ]; then docker run benjaminn13/pid-workspace-ci:ubuntu-18.04 bash -c "git config --global user.name "CI Bot" && git config --global user.email dontcare@CI.com && make upgrade && make deploy package=open-phri && cd ../packages/open-phri/build/ && cmake -DBUILD_AND_RUN_TESTS=ON .. && cmake .. && make build force=true"; fi
    - if [ $TRAVIS_BRANCH = 'integration' ]; then docker run benjaminn13/pid-workspace-ci:ubuntu-16.04 bash -c "git config --global user.name "CI Bot" && git config --global user.email dontcare@CI.com && make upgrade && make deploy package=open-phri && cd ../packages/open-phri/build/ && git checkout integration && cmake -DBUILD_AND_RUN_TESTS=ON .. && cmake .. && make build"; fi
    - if [ $TRAVIS_BRANCH = 'integration' ]; then docker run benjaminn13/pid-workspace-ci:ubuntu-18.04 bash -c "git config --global user.name "CI Bot" && git config --global user.email dontcare@CI.com && make upgrade && make deploy package=open-phri && cd ../packages/open-phri/build/ && git checkout integration && cmake -DBUILD_AND_RUN_TESTS=ON .. && cmake .. && make build"; fi
