sudo: required

language: c++

services:
  - docker

before_install:
    - docker pull benjaminn13/pid-workspace-ci

script:
    - docker run benjaminn13/pid-workspace-ci bash -c "make deploy package=open-phri && cd ../packages/open-phri/build/ && cmake -DBUILD_AND_RUN_TESTS=ON .. && cmake .. && make build force=true"
