version: 2

jobs:
  "build_ubuntu1404":
    docker:
      - image: benjaminn13/pid-workspace-ci:ubuntu-14.04
    working_directory: /home/piduser/pid-workspace/pid
    steps:
      - run: make upgrade && make deploy package=open-phri && cd ../packages/open-phri && git fetch --all && git checkout $CIRCLE_BRANCH && cd build && cmake -DBUILD_AND_RUN_TESTS=ON .. && cmake .. && make build force=true
  "build_ubuntu1604":
    docker:
      - image: benjaminn13/pid-workspace-ci:ubuntu-16.04
    working_directory: /home/piduser/pid-workspace/pid
    steps:
      - run: make upgrade && make deploy package=open-phri && cd ../packages/open-phri && git fetch --all && git checkout $CIRCLE_BRANCH && cd build && cmake -DBUILD_AND_RUN_TESTS=ON .. && cmake .. && make build force=true
  "build_ubuntu1804":
    docker:
      - image: benjaminn13/pid-workspace-ci:ubuntu-18.04
    working_directory: /home/piduser/pid-workspace/pid
    steps:
      - run: make upgrade && make deploy package=open-phri && cd ../packages/open-phri && git fetch --all && git checkout $CIRCLE_BRANCH && cd build && cmake -DBUILD_AND_RUN_TESTS=ON .. && cmake .. && make build force=true


workflows:
  version: 2
  build:
    jobs:
      - "build_ubuntu1404"
      - "build_ubuntu1604"
      - "build_ubuntu1804"
