version: 2

jobs:
  "build_ubuntu1604":
    docker:
      - image: benjaminn13/pid-workspace-ci:ubuntu-16.04
    working_directory: /home/piduser/pid-workspace/pid
    steps:
      - run: make upgrade && make deploy package=open-phri branch=$CIRCLE_BRANCH test=true
  "build_ubuntu1804":
    docker:
      - image: benjaminn13/pid-workspace-ci:ubuntu-18.04
    working_directory: /home/piduser/pid-workspace/pid
    steps:
      - run: make upgrade && make deploy package=open-phri branch=$CIRCLE_BRANCH test=true


workflows:
  version: 2
  build:
    jobs:
        - "build_ubuntu1604"
        - "build_ubuntu1804"
